keys:
  - &admin age1v492u0esm92zy34e33xd9m7z4jt3v03j233ar75k5m7s0rlxes0sxadr2t
  - &smithoo4 age1l9ql4gyqka00sndqzjx7cz0k7ymh3vle7f5ppdyvpntlz5lfme9syv8gym

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *smithoo4
